baseurl = "https://www.bridgetmaddisoncbt.co.uk/"
languageCode = "en-us"
title = "Bridget Maddison CBT"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10


[params]
	author = "Bridget Maddison"
	description = "Bridget Maddison CBT"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.png"
	# or use Gravatar by adding an MD5-hash of your email address
	gravatar = ""

	headerText = ""
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = "header4.jpg"
	copyright = "Bridget Maddison"


	[params.social]
	# Insert your accout name and the icon will be shown in the right menu
		rss = false
		email = ""
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = "bridgetmaddisoncbt"
		flickr = ""
		github = ""
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = "bridgetmaddiso1"
		wordpress = ""
		youtube = ""

[markup.goldmark.renderer]
unsafe = true
